### ISSUE TITLE
Set a timeout limit on SQL queries via the web-interface

### ISSUE THREAD

**Issue by thespacedoctor** [lsst-uk/lasair-project-management#16]
We want to give users the freedom to write their own read-only querues but still protect the database from very slow queries that would hog database resources. We can do this by injecting a query timeout - but how?

**Comment by RoyWilliams** [comment]
From https://mysqlserverteam.com/server-side-select-statement-timeouts/ Looks like it works ... here is a query that takes 3 minutes, and here it is restricted to 5 seconds execution:

mysql> SELECT objectId FROM candidates WHERE objectId NOT IN (SELECT objectId FROM objects)  GROUP BY objectId HAVING count(*) > 2;
Empty set (2 min 30.19 sec)

mysql> SELECT /*+ MAX_EXECUTION_TIME(5000) */ objectId FROM candidates WHERE objectId NOT IN (SELECT objectId FROM objects) GROUP BY objectId HAVING count(*) > 2;
ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded

**Comment by RoyWilliams** [comment]
Here is a 5 second timeout

mysql> SELECT /*+ MAX_EXECUTION_TIME(5000) */ objectId FROM candidates WHERE objectId NOT IN (SELECT objectId FROM objects) GROUP BY objectId HAVING count(*) > 2;
ERROR 3024 (HY000): Query execution was interrupted, maximum statement execution time exceeded

mysql> SELECT objectId FROM candidates WHERE objectId NOT IN (SELECT objectId FROM objects)  GROUP BY objectId HAVING count(*) > 2;
Empty set (2 min 30.19 sec)
