### ISSUE TITLE
Request: galaxy effective radius in sherlock_classifications table

### ISSUE THREAD

**Issue by mnicholl** [lsst-uk/lasair-project-management#240]
It would be really useful for some queries to be able to use host galaxy radius in the tables (the half light radius, Kron radius, or whatever measure is provided by many catalogs). E.g. if I only want transients in compact dwarf galaxies.

The older version of Lasair included major_axis_arcsec from NED, but in Lasair-iris no measurements are reported. Using the Kron radius from PanSTARRS, or petrosian radius from Sloan, would probably be most useful and cover the largest number of galaxies.

Ideally this could be included information both as angular radius and physical radius if distance is known.

**Comment by RoyWilliams** [comment]
Matt -- Can you pick out what you want from the full Sherlock output? -- Roy

{
  "classifications": {
    "ZTF21abbzhvg": [
      "NT",
      "The transient is synonymous with <em><a href=\"https://ned.ipac.caltech.edu/cgi-bin/objsearch?objname=2MASXJ16222678+0737007&extend=no&hconst=73&omegam=0.27&omegav=0.73&corr_z=1&out_csys=Equatorial&out_equinox=J2000.0&obj_sort=RA+or+Longitude&of=pre_text&zv_breaker=30000.0&list_limit=5&img_stamp=YES\">2MASXJ16222678+0737007</a></em>; an r=16.51 mag galaxy found in the NED/SDSS catalogues. It's located 0.4\" (0.5 Kpc) from the galaxy core. A host z=0.072 implies a <em>m - M =</em> 37.56."
    ]
  },
  "crossmatches": [
    {
      "catalogue_object_subtype": "multiple",
      "catalogue_object_id": "2MASXJ16222678+0737007",
      "z": 0.072089,
      "unkMag": 17.1,
      "separationArcsec": 0.3710646029979128,
      "northSeparationArcsec": "-0.4",
      "eastSeparationArcsec": "0.0",
      "association_type": "NT",
      "catalogue_view_name": "multiple",
      "transient_object_id": "ZTF21abbzhvg",
      "catalogue_table_name": "NED/SDSS",
      "catalogue_table_id": 68,
      "catalogue_view_id": 29,
      "classificationReliability": 1,
      "scale": 1.373188,
      "distance": 325.549219,
      "distance_modulus": 37.563083,
      "major_axis_arcsec": 24.599999999999998,
      "direct_distance": null,
      "direct_distance_scale": null,
      "direct_distance_modulus": null,
      "catalogue_object_type": "galaxy",
      "search_name": "multiple",
      "raDeg": 245.611531331531,
      "decDeg": 7.616751004102683,
      "original_search_radius_arcsec": "multiple",
      "physical_separation_kpc": 0.5095414600614979,
      "merged_rank": null,
      "photoZ": null,
      "photoZErr": null,
      "_r": 16.5142,
      "_rErr": 0.015218,
      "_g": 17.2973,
      "_gErr": 0.0170546,
      "_i": 16.0778,
      "_iErr": 0.0133541,
      "_z": 15.9029,
      "_zErr": 0.0260184,
      "_u": 19.2743,
      "_uErr": 0.15441,
      "rankScore": 952.0254770730031,
      "rank": 1
    },
    {
      "catalogue_object_subtype": "G",
      "catalogue_object_id": "2MASX J16222678+0737007",
      "z": 0.072089,
      "unkMag": 17.1,
      "separationArcsec": 0.3739051362534249,
      "northSeparationArcsec": "-0.4",
      "eastSeparationArcsec": "0.0",
      "association_type": "NT",
      "catalogue_view_name": "tcs_view_galaxy_ned_stream",
      "transient_object_id": "ZTF21abbzhvg",
      "catalogue_table_name": "NED",
      "catalogue_table_id": 68,
      "catalogue_view_id": 29,
      "classificationReliability": 1,
      "scale": 1.373188,
      "distance": 325.549219,
      "distance_modulus": 37.563083,
      "major_axis_arcsec": 24.599999999999998,
      "direct_distance": null,
      "direct_distance_scale": null,
      "direct_distance_modulus": null,
      "catalogue_object_type": "galaxy",
      "search_name": "ned spec galaxy physical (within 1.2 * major axis) (redshift distance)",
      "raDeg": 245.6115417,
      "decDeg": 7.61675,
      "original_search_radius_arcsec": 36.41162025884292,
      "physical_separation_kpc": 0.5134420462415681,
      "merged_rank": 1,
      "rankScore": 952.0254770730031
    },
    {
      "catalogue_object_subtype": 3,
      "catalogue_object_id": 1237668348149498184,
      "z": 0.0720786,
      "_u": 19.2743,
      "_uErr": 0.15441,
      "_g": 17.2973,
      "_gErr": 0.0170546,
      "_r": 16.5142,
      "_rErr": 0.015218,
      "_i": 16.0778,
      "_iErr": 0.0133541,
      "_z": 15.9029,
      "_zErr": 0.0260184,
      "separationArcsec": 0.3710646029979128,
      "northSeparationArcsec": "-0.370137",
      "eastSeparationArcsec": "-0.026435",
      "association_type": "NT",
      "catalogue_view_name": "tcs_view_galaxy_sdss_spect_galaxies_qsos_dr12",
      "transient_object_id": "ZTF21abbzhvg",
      "catalogue_table_name": "SDSS DR12 SpecObjAll Table",
      "catalogue_table_id": 48,
      "catalogue_view_id": 14,
      "classificationReliability": 1,
      "scale": 1.3730061,
      "distance": 325.4998917,
      "distance_modulus": 37.5627542,
      "major_axis_arcsec": null,
      "direct_distance": null,
      "direct_distance_scale": null,
      "direct_distance_modulus": null,
      "catalogue_object_type": "galaxy",
      "search_name": "sdss spec sn physical (redshift distance)",
      "raDeg": 245.611531331531,
      "decDeg": 7.616751004102683,
      "original_search_radius_arcsec": 36.416444180400944,
      "physical_separation_kpc": 0.5094739634102126,
      "merged_rank": 1,
      "rankScore": 952.0254770730031
    }
  ]
}

**Comment by thespacedoctor** [comment]
Hi @mnicholl - I will need to do a little work on Sherlock to integrate the Kron & petrosian radiui. Unfortunately I currently don't have SDSS petrosian radii in Sherlock's SDSS tables, this could be rectified while upgrading the SDSS tables from DR12 to DR16. But I'm assuming the PanSTARRS Kron radii are much greater value in this context? These I do have.

It would be ideal if I could integrate these values into the current Sherlock schema. My proposal would be to use the `major_axis_arcsec` column that currently only hosts NED values for the galaxy diameter.

The PanSTARRS Kron and SDSS petrosian radii are both measured in arcsec, so I would simply multiply these values by 2 and have them populate the `major_axis_arcsec` column.

I have *griyz* Kron radii for PanSTARRS. Which filter do you prefer to port into the Sherlock results? r-band?

**Comment by mnicholl** [comment]
Hi @RoyWilliams @thespacedoctor , thanks for replies. In answer to Roy first, major_axis_arcsec sounds like the right one to include in the lasair tables. The magnitudes _g, _r etc would also be very useful for other things.

Dave: Kron radii as good as anything else I think, so starting with those is perfect. And yes including them within the current schema as major_axis_arcsec should still be easy to work with for the user. As for the filter my instinct is r but probably any of gri would be fine, perhaps if there is an object with no radius in r for some reason it could then grab the value from another band, if that isn't too annoying to have to build in...

**Comment by thespacedoctor** [comment]
I will add the `major_axis_arcsec` value into the sherlock lite output as this is (almost) homogenizable and so can be placed in the top-level crossmatch attributes. With _g and _r we are getting back into the catalogue specific territory, so if these are really needed then we would need to revisit reintroducing the old sherlock_crossmatch table.

**Comment by mnicholl** [comment]
Hi Dave, don't worry about the _g and _r then, using the mag and filter as currently implemented are fine for now. I guess looking ahead for LSST, the ugrizy LSST mags of the nearest object should be in there!

**Comment by thespacedoctor** [comment]
This is complete.
