### ISSUE TITLE
Zero Orphans in Lasair-iris

### ISSUE THREAD

**Issue by chrisfrohmaier** [lsst-uk/lasair-project-management#248]
I'm interested in objects classified by Sherlock as ORPHAN. In the Lasair-iris query builder I construct the command:

`SELECT /*+ MAX_EXECUTION_TIME(300000) */ objects.objectId FROM objects, sherlock_classifications WHERE objects.objectId=sherlock_classifications.objectId AND classification="ORPHAN" LIMIT 1000 OFFSET 0`

This returns zero objects.

In original Lasair, I ran a similar query:
`SELECT /*+ MAX_EXECUTION_TIME(300000) */ objects.objectId FROM objects,sherlock_classifications WHERE objects.primaryId = sherlock_classifications.transient_object_id AND objects.jdmax > JDNOW() - 500.00000 AND classification="ORPHAN" LIMIT 1000 OFFSET 0`

and find 1,000+ ORPHANS. 

Are ORPHANs ingested into Lasair-iris?

**Comment by RoyWilliams** [comment]
This is strange .... theres only one!
mysql> select classification, count(*) from sherlock_classifications group by classification;
+----------------+----------+
| classification | count(*) |
+----------------+----------+
| AGN            |   125436 |
| BS             |   231127 |
| CV             |      985 |
| NT             |    11980 |
| ORPHAN         |        1 |
| SN             |   281710 |
| UNCLEAR        |     6480 |
| VS             |  4118523 |
+----------------+----------+

**Comment by RoyWilliams** [comment]
Hi Chris -- there was a bug and we were not recording the ORPHAN classification properly. It is fixed now, so they are building up, now 24 in the last 3 hours.

**Comment by tms-epcc** [comment]
Moved to community
