### ISSUE TITLE
Review and refresh website design

### ISSUE THREAD

**Issue by RoyWilliams** [lsst-uk/lasair-project-management#254]
- [x] Make wiki page for discussion [here](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2556624903/Review+and+Refresh+Lasair+website)
- [x] Build [development website](http://192.41.108.37:8080/)
- [x] Prototype new ideas on dev website
- [x] Define user types and user stories
- [x] Complete [user story analysis](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2556624903/Review+and+Refresh+Lasair+website)
- [x] Get [usability analysis from key users](https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/2556624903/Review+and+Refresh+Lasair+website) 
- [x] Sketch and discuss new look and feel (  @thespacedoctor, Meg )
    * Design structure to fit the user stories (simple graphic design)
    * Look at exemplar websites for design ideas
- [x] Debate issue of whether to refactor on API
- [x] Complete design ready for Cycle 6 construction
- [x] Decide how to satisfy MS19 and D3.2.2 
- [x] Documentation 
- [x] Structure: for who, what media, faq, reference, search
- [ ] Tutorials
- [ ] Hackathon day ( @thespacedoctor )

**Comment by tms-epcc** [comment]
06/OCT/22
- in cycle-7 the following added to the main checkbox list above
    - Documentation and tutorials
    - Structure: for who, what media, faq, reference, search
    - Hackathon day ( @thespacedoctor )

**Comment by tms-epcc** [comment]
14/DEC/22
- @thespacedoctor finishing the web interface
- @RoyWilliams writing the documentation but blocked since needing screenshots form the web interface

**Comment by tms-epcc** [comment]
03/MAY/23
- as agreed with @RoyWilliams this is done now that documentation is published
