### ISSUE TITLE
Modify ingest.py to call pip installed insert code & build test

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair-project-management#274]
The code to do Cassandra inserts is pulled almost verbatim from my gkdbutils code.  I (Ken) need to modify the gkdbutils code so that the inserter code can be included directly (saves having to maintain two identical code bases).  Then modification of ingest.py code required to include the relevant function.  It would also be useful to have a unit test, though the test is really an integration test (since it requires access to a test Cassandra instance).

**Comment by tms-epcc** [comment]
Superseded
