### ISSUE TITLE
Change local ansible templates to refer to relative directory structure (or use role templates)

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair-project-management#275]
Ansible playbooks (e.g. lasair-db.yml and webserver.yml) refer to templates in absolute directories. Creating this issue so I can track a pull request with the fix (though Gareth has probably done this already in his setup).

The fix is to make addressing of source templates relative (or better still, rearrange the playbook as a role with a templates directory).

**Comment by tms-epcc** [comment]
DONE
