### ISSUE TITLE
Latest Lasair long-term plan

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lasair-project-management#295]

**Comment by tms-epcc** [comment]
14/JUN/23
- @andyxerxes drafting this

**Comment by andyxerxes** [comment]
Terry

hows this for better ARIC wording?



We set individual responsibilities for Lasair using a ARIC model, i.e. specifying who is {\em Accountable}, i.e. to the Consortium, and to STFC, for seeing that the deliverables are achieved; who is {\em Responsible}, i.e who will in practice undertake the work; who should be {\em Informed}, i.e. kept abreast of progress, key changes, etc; and who needs to be {\em Consulted}, i.e. parties affected by changes in Lasair, who should therefore be made aware of such changes, especially ones they may need to have input into.



andy

The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336. Is e buidheann carthannais a th’ ann an Oilthigh Dhùn Èideann, clàraichte an Alba, àireamh clàraidh SC005336.

**Comment by tms-epcc** [comment]
> Terry hows this for better ARIC wording? We set individual responsibilities for Lasair using a ARIC model, i.e. specifying who is {\em Accountable}, i.e. to the Consortium, and to STFC, for seeing that the deliverables are achieved; who is {\em Responsible}, i.e who will in practice undertake the work; who should be {\em Informed}, i.e. kept abreast of progress, key changes, etc; and who needs to be {\em Consulted}, i.e. parties affected by changes in Lasair, who should therefore be made aware of such changes, especially ones they may need to have input into. andy The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336. Is e buidheann carthannais a th’ ann an Oilthigh Dhùn Èideann, clàraichte an Alba, àireamh clàraidh SC005336.

@andyxerxes - yes, looks good to me.

**Comment by andyxerxes** [comment]
ok cool

From: Terry Sloan ***@***.***>
Reply to: lsst-uk/lasair-project-management ***@***.***>
Date: Wednesday, 14 June 2023 at 12:18
To: lsst-uk/lasair-project-management ***@***.***>
Cc: Andy Lawrence ***@***.***>, Mention ***@***.***>
Subject: Re: [lsst-uk/lasair-project-management] Latest Lasair long-term plan (Issue #295)

This email was sent to you by someone outside the University.
You should only click on links or attachments if you are certain that the email is genuine and the content is safe.

Terry hows this for better ARIC wording? We set individual responsibilities for Lasair using a ARIC model, i.e. specifying who is {\em Accountable}, i.e. to the Consortium, and to STFC, for seeing that the deliverables are achieved; who is {\em Responsible}, i.e who will in practice undertake the work; who should be {\em Informed}, i.e. kept abreast of progress, key changes, etc; and who needs to be {\em Consulted}, i.e. parties affected by changes in Lasair, who should therefore be made aware of such changes, especially ones they may need to have input into. andy The University of Edinburgh is a charitable body, registered in Scotland, with registration number SC005336. Is e buidheann carthannais a th’ ann an Oilthigh Dhùn Èideann, clàraichte an Alba, àireamh clàraidh SC005336.

@andyxerxes<https://github.com/andyxerxes> - yes, looks good to me.

**Comment by andyxerxes** [comment]
Substantially complete draft completed and discussed at Zoom 2023-07-19. Follow on discussion by Roy and Andy, and Roy has made further changes

**Comment by tms-epcc** [comment]
30/AUG/23
- made publicly available from LSST:UK Confluence wiki at  
https://lsst-uk.atlassian.net/wiki/download/attachments/1146928/LUSC-C02-Lasair-LongTermPlan-V1.pdf?api=v2
