### ISSUE TITLE
Lasair WP3.5 brief

### ISSUE THREAD

**Issue by tms-epcc** [lsst-uk/lasair-project-management#298]
See https://lsst-uk.atlassian.net/wiki/spaces/LUSC/pages/3224141825/Brief+for+WP3.5+Lasair+the+UK+s+community+broker

**Comment by andyxerxes** [comment]
Stephen started this?

**Comment by tms-epcc** [comment]
19/JUL/23
- @tms-epcc started draft based on Phase C proposal with expectation this will be completed AFTER the latest version of the Lasair LTP is ready.

**Comment by tms-epcc** [comment]
04/OCT/23
 - @RoyWilliams will update the WP3.5 brief based on the long-term plan and the briefs for the corresponding Phase B WPs

**Comment by tms-epcc** [comment]
12/OCT/23
- Roy and Terry have updated the brief further

**Comment by tms-epcc** [comment]
15/NOV/23
- no concerns raised
