### ISSUE TITLE
Detach this fork from original parent 

### ISSUE THREAD

**Issue by Zarquan** [lsst-uk/lasair-project-management#308]
Long long ago, in the before times, the `lasair-project-management` repository started as a fork of `https://github.com/Zarquan/lasair`.

As far as I can tell none of the original code base remains in the `lasair-project-management`.

Suggest we start by separating the two and then work out what to do with `https://github.com/Zarquan/lasair`.

**Comment by Zarquan** [comment]
Looks like there are two ways to do it.
1. Delete the upstream repository. See [what-happens-to-the-forks-when-deleting-the-original-repository](https://stackoverflow.com/questions/53052745/what-happens-to-the-forks-when-deleting-the-original-repository)
2. Delete and re-create this repository. See [detaching-a-fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork)

Is anyone particularly attached to the old code in https://github.com/Zarquan/lasair ?

**Comment by tms-epcc** [comment]
Will not cause any issues if not done.
