### ISSUE TITLE
No indexes on the objects table

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair-project-management#65]
I just spotted that there are no indexes on ANY column in objects apart from htm16, and objectID (and that stale flag we don't use anymore).  (Good columns to index might be sherlock_classification, jdmin, jdmax.)

Hence queries will take a long time!  We can create as many features as we like, but if we don't index them, all queries relying on them will take forever!  (Full table scan required.)

Am I missing something?

**Comment by thespacedoctor** [comment]
Hi Ken, we definitely added indexes to the most heavily used columns. See issue #11 for example; this was 18 months ago so something changed since then.

**Comment by RoyWilliams** [comment]
(1) Right now lasair-db and lasair-dev-db have the same indexes
  PRIMARY KEY (`primaryId`),
  UNIQUE KEY `objectId_UNIQUE` (`objectId`),
  KEY `htmid16idx` (`htm16`),
  KEY `idx_objectId_stale` (`objectId`,`stale`)

(2) The one involving 'stale' can be dropped

(3) Can you tell me what indexes you recommend? You mention jdmin, jdmax, sounds great.

(4) But surely sherlock_classification belongs in the sherlock table, not in the objects table? The documentation doesn't mention objects.sherlock_classification.

(4) Can you make the update first on lasair-dev-db? (make sure it doesn't take a hundred years to make the index). 

(5) Can the database be in some kind of single user for this? I think there is a line "bind-address" in the config that can be commented out.

(6) Lets run (2) - (5) on lasair-dev so we know what we are doing and have a working script. But then IMPORTANT Must coordinate with Mark Holliman, who will shut down lasair to change the VM attributes.

**Comment by thespacedoctor** [comment]
Thanks Roy. 

There are < 20e6 rows in the objects table so should be trivial amount of time to add the indexes. I can certainly do it on the dev machine first. I can do it this evening - or later this morning if Mark is quick off the mark.

> Can you tell me what indexes you recommend? You mention jdmin, jdmax, sounds great.

We should really go to town with the indexes on this table as it's the main table that users are querying from webpages and juptyerhub. 

![](https://live.staticflickr.com/65535/49745601442_084df29d50_o.png)

Looking at the column list above I would nearly add an index per column. How about these ones? @genghisken ?

`primaryId`
`objectId`
`ncand`
`ramean`
`rastd`
`decmean`
`decstd`
`maggmin`
`maggmax`
`maggmedian`
`maggmean`
`magrmin`
`magrmax`
`magrmedian`
`magrmean`
`latestgmag`
`latestrmag`
`jdmin`
`jdmax`
`sherlock_classification`
`glatmean`
`glonmean`
`htm16`
`sgmag1`
`srmag1`
`sgscore1`
`distpsnr1`
`ncandgp`

> (4) But surely sherlock_classification belongs in the sherlock table, not in the objects table? The documentation doesn't mention objects.sherlock_classification.

There is a `sherlock_classification` column in objects table.

> Can the database be in some kind of single user for this? I think there is a line "bind-address" in the config that can be commented out.

No need - all other processes will just wait until the reindexing is done. MySQL is smart enough to worry about this for us.

> (6) Lets run (2) - (5) on lasair-dev so we know what we are doing and have a working script. 

Deal

**Comment by RoyWilliams** [comment]
Doesnt the ingestion slow down if there are lots of indexes?

**Comment by thespacedoctor** [comment]
The bulk of the inserts are occurring on the `candidates` table.  The number of inserts to objects table is ~33,000 per night (20 million /  600 days). This can be inserted in ~10s.

**Comment by thespacedoctor** [comment]
I've executed the following on the lasair-db machine and @genghisken has done the same on lasair-db-dev (I don't have access):

```sql
ALTER TABLE `ztf`.`objects` 
ADD INDEX `idx_ncand` (`ncand` ASC),
ADD INDEX `idx_ramean` (`ramean` ASC),
ADD INDEX `idx_rastd` (`rastd` ASC),
ADD INDEX `idx_decmean` (`decmean` ASC),
ADD INDEX `idx_decstd` (`decstd` ASC),
ADD INDEX `idx_maggmin` (`maggmin` ASC),
ADD INDEX `idx_maggmax` (`maggmax` ASC),
ADD INDEX `idx_maggmedian` (`maggmedian` ASC),
ADD INDEX `idx_maggmean` (`maggmean` ASC),
ADD INDEX `idx_magrmin` (`magrmin` ASC),
ADD INDEX `idx_magrmax` (`magrmax` ASC),
ADD INDEX `idx_magrmedian` (`magrmedian` ASC),
ADD INDEX `idx_magrmean` (`magrmean` ASC),
ADD INDEX `idx_latestgmag` (`latestgmag` ASC),
ADD INDEX `idx_latestrmag` (`latestrmag` ASC),
ADD INDEX `idx_jdmin` (`jdmin` ASC),
ADD INDEX `idx_jdmax` (`jdmax` ASC),
ADD INDEX `idx_sherlock_classification` (`sherlock_classification` ASC),
ADD INDEX `idx_glatmean` (`glatmean` ASC),
ADD INDEX `idx_glonmean` (`glonmean` ASC),
ADD INDEX `idx_htm16` (`htm16` ASC),
ADD INDEX `idx_sgmag1` (`sgmag1` ASC),
ADD INDEX `idx_srmag1` (`srmag1` ASC),
ADD INDEX `idx_sgscore1` (`sgscore1` ASC),
ADD INDEX `idx_distpsnr1` (`distpsnr1` ASC),
ADD INDEX `idx_ncandgp` (`ncandgp` ASC),
DROP INDEX `idx_objectId_stale` ;
```

Took ~20 mins to complete and has drastically sped up most queries. Please test your favourite queries and report back if you have any speed issues.

**Comment by thespacedoctor** [comment]
Done
